version: "3.8"

services:
  db:
    image: postgres
    restart: always
    container_name: comunicacao_interna_db
    environment:
      POSTGRES_USER: teste
      POSTGRES_PASSWORD: teste
      POSTGRES_DB: comunicacao_interna
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
